# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=io.github.mintynoura.locktouch
archives_base_name=locktouch

# Dependencies
fabric_version=0.140.0+1.21.11